{
 "title": "MLOps com Monitoramento do LLM",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total de Perguntas Respondidas",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  COUNT(*) Total_Question_Answered\r\nFROM llm_avaliacao \r\n--GROUP BY 1"
    }
   ]
  },
  {
   "title": "Feedbacks Preenchidos Pelos Usuários",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  COUNT(*) Users_Filled_Feedback\r\nFROM llm_feedback "
    }
   ]
  },
  {
   "title": "Taxa de Satisfação dos Usuários com o LLM",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n\r\n  COUNT(CASE WHEN is_satisfied = TRUE THEN id ELSE NULL END)/COUNT(id)::float AS Users_Satisfaction\r\nFROM llm_feedback "
    }
   ]
  },
  {
   "title": "Tempo de Resposta do LLM",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  created_time,\r\n  response_time\r\nFROM llm_avaliacao "
    }
   ]
  },
  {
   "title": "Score de Performance do LLM",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  created_time,\r\n  llm_score,\r\n  mrr_score,\r\n  hit_rate_score\r\nFROM llm_avaliacao "
    }
   ]
  }
 ]
}